name: encrypted_url_preview
description: A utility to interact with proxy server and fetch url preview
version: 1.0.0

environment:
  sdk: ^3.1.2

dependencies:
  basic_utils: ^5.7.0
  pointycastle: ^3.7.4


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  html: ^0.15.4
